name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    strategy:
      fail-fast: false
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
         submodules: "recursive"
    - name: Build
      run: cargo build --all --verbose
    - name: Examples
      run: cargo build --all --verbose --examples
    - name: Run tests
      run: cargo test --all --verbose
    - name: Check formatting
      run: cargo fmt --all -- --check
  system-libs:
    strategy:
      fail-fast: false
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install deps
      run: |
        sudo -n apt-get update
        sudo -n apt-get install -y libmosquitto-dev
    - name: Build
      run: cd mosquitto-rs && cargo build --no-default-features --verbose
    - name: Examples
      run: cd mosquitto-rs && cargo build --no-default-features --verbose --examples
    - name: Run tests
      run: cd mosquitto-rs && cargo test --no-default-features --verbose
  mac:
    strategy:
      fail-fast: false
    runs-on: "macos-latest"
    steps:
    - uses: actions/checkout@v2
      with:
         submodules: "recursive"
    - name: Build
      run: cargo build -p mosquitto-rs --all-features --verbose
    - name: Examples
      run: cargo build -p mosquitto-rs --all-features --verbose --examples
    - name: Run tests
      run: cargo test -p mosquitto-rs --all-features --verbose
  windows:
    strategy:
      fail-fast: false
    runs-on: "windows-latest"
    steps:
    - uses: actions/checkout@v2
      with:
         submodules: "recursive"
    - name: Build
      run: cargo build -p mosquitto-rs --all-features --verbose
    - name: Examples
      run: cargo build -p mosquitto-rs --all-features --verbose --examples
    - name: Run tests
      run: cargo test -p mosquitto-rs --all-features --verbose
